import type { Metadata } from 'next';
import { Roboto, Rubik } from 'next/font/google';
import '../assets/styles/globals.scss';
import Providers from '@/providers/Providers';
// import Providers from '@/providers/Providers';

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	variable: '--font-roboto',
	display: 'swap',
});
const rubik = Rubik({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	variable: '--font-rubik',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

	return (
		<html lang="en" className="transition-all">
			<body
							>
							<Providers>	{children}</Providers>
			</body>
		</html>
	);
}
